version: '3.8'

services:
  # Backend Service (FastAPI)
  backend:
    build: ./backend
    container_name: chat_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Mounts local code (good for dev, remove in prod if not needed)
    environment:
      - DATABASE_URL=mongodb+srv://vikram:Vroy2005@chat.9xlbtw3.mongodb.net/?retryWrites=true&w=majority&appName=Chat
    restart: unless-stopped

  # Frontend Service (React + Nginx)
  frontend:
    build: ./frontend
    container_name: chat_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
