version: '3.8'

services:
  # MongoDB Database Service
  db:
    image: mongo:latest
    container_name: chat_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # Backend Service (FastAPI)
  backend:
    build: ./backend
    container_name: chat_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Mounts local code for live-reloading during development
    environment:
      # Use the service name 'db' as the hostname for the database
      - DATABASE_URL=mongodb://db:27017/
    depends_on:
      - db
    restart: unless-stopped

  # Frontend Service (React + Nginx)
  frontend:
    build: ./frontend
    container_name: chat_frontend
    ports:
      - "80:80" # Map host port 3000 to Nginx container port 80
    depends_on:
      - backend
    restart: unless-stopped

volumes:

  mongo_data:
