version: '3.8'

services:
  # Backend Service (FastAPI)
  backend:
    build: ./backend
    container_name: chat_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=mongodb+srv://vikram:Vroy2005@chat.9xlbtw3.mongodb.net/?retryWrites=true&w=majority&appName=Chat
    restart: unless-stopped

  # Frontend Service (React + Nginx)
  frontend:
    build: ./frontend
    container_name: chat_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
      - cadvisor

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

  # cAdvisor (Container Monitoring)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  # Node Exporter (Host Metrics)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

volumes:
  grafana-storage:
